#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

function walk(dir, fileList = []) {
  const files = fs.readdirSync(dir);
  for (const f of files) {
    const full = path.join(dir, f);
    const stat = fs.statSync(full);
    if (stat.isDirectory()) {
      // skip node_modules, .git
      if (f === 'node_modules' || f === '.git') continue;
      walk(full, fileList);
    } else {
      fileList.push(full);
    }
  }
  return fileList;
}

function searchFiles(rootDirs, searchTerm) {
  const results = [];
  for (const root of rootDirs) {
    if (!fs.existsSync(root)) continue;
    const files = walk(root);
    for (const file of files) {
      // only scan text files
      const ext = path.extname(file).toLowerCase();
      if (!['.js', '.ts', '.json', '.md', '.jsx', '.tsx'].includes(ext)) continue;
      try {
        const txt = fs.readFileSync(file, 'utf8');
        if (txt.toLowerCase().includes(searchTerm.toLowerCase())) {
          const lines = txt.split(/\r?\n/);
          const hits = [];
          for (let i = 0; i < lines.length; i++) {
            if (lines[i].toLowerCase().includes(searchTerm.toLowerCase())) hits.push({ line: i + 1, text: lines[i].trim() });
          }
          results.push({ file, hits });
        }
      } catch (e) {
        // ignore binary or unreadable files
      }
    }
  }
  return results;
}

function renderAudit(results) {
  const lines = [];
  lines.push('# Yelp API Audit');
  lines.push('');
  lines.push('Generated by `scripts/yelp_audit.js` — lists files referencing "yelp" and sample lines.');
  lines.push('');
  for (const r of results) {
    lines.push(`## ${r.file}`);
    lines.push('');
    for (const h of r.hits.slice(0, 10)) {
      lines.push(`- L${h.line}: ${h.text}`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

function main() {
  const targets = ['api', 'workers', 'scripts', 'jobs'];
  const results = searchFiles(targets, 'yelp');
  const out = renderAudit(results);
  const outDir = path.resolve(process.cwd(), 'docs');
  if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });
  const outPath = path.join(outDir, 'YELP_AUDIT.md');
  fs.writeFileSync(outPath, out, 'utf8');
  console.log('Wrote', outPath);
}

if (require.main === module) main();
